name: .NET CI/CD

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Setup Azure CLI
      uses: azure/setup-azure@v3

    - name: Restore dependencies
      run: dotnet restore

    - name: Run Unit Tests
      run: dotnet test **/SunatIntegration.Tests.csproj --no-build --configuration Release --collect:"XPlat Code Coverage" --verbosity normal

    - name: Run Integration Tests
      run: dotnet test **/SunatIntegration.IntegrationTests.csproj --no-build --configuration Release --verbosity normal

    - name: Publish Azure Function
      run: dotnet publish **/SunatIntegration.Functions.csproj -c Release -o ./publish --verbosity normal

    - name: Deploy to Azure Function App
      uses: azure/functions-action@v1
      with:
        app-name: <NOMBRE_DE_TU_FUNCTION_APP>
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        package: ./publish
